=== panel_pull ===
a number of loose screws clatter to the floor as the panel swings open. Behind it lies a mess of cables and cords, all connected by a small pixilated screen with a keypad. Exodus’s logo flashes in blue neon on the static-y mainframe. You glance at the back of the panel, finding a small string of numbers scratched into the metal… 
* ...“5241542119”...-> END